# Site settings
title: Eclypse Z7 Notes
description: Notes on the Eclypse Z7 development board
baseurl: /eclypse-z7-notes
url: https://pavel-demin.github.io
permalink: /:slug/

source-link: https://github.com/pavel-demin/eclypse-z7-notes
issues-link: https://github.com/pavel-demin/eclypse-z7-notes/issues

release-image: https://github.com/pavel-demin/eclypse-z7-notes/releases/download/20230222/eclypse-z7-alpine-3.14-armv7-20230222.zip

extio-file: https://www.dropbox.com/scl/fi/pl8gfjn2ay267or1zkohu/extio_red_pitaya.dll?rlkey=zhmv6qktymfeno8bdap94noq9&dl=1

# Build settings
markdown: kramdown
highlighter: rouge
