# Site settings
title: Eclypse Z7 Notes
description: Notes on the Eclypse Z7 development board
baseurl: /eclypse-z7-notes
url: https://pavel-demin.github.io

release-image: https://github.com/pavel-demin/eclypse-z7-notes/releases/download/20230222/eclypse-z7-alpine-3.14-armv7-20230222.zip

# Build settings
markdown: kramdown
highlighter: rouge
